/// Represents a single membership fee bill/invoice raised for a member.
/// Bills are raised on member onboarding and automatically ahead of each
/// membership renewal cycle so admins can track exactly which dues are
/// outstanding, due soon, or already settled.
class BillModel {
  final String id;
  final String billNumber;
  final String memberId;
  final String memberName;
  final String memberPhone;
  final String? membershipId;
  final String planName;
  final double amount;
  final DateTime billDate;
  final DateTime dueDate;
  final String status; // Pending, Overdue, Partially Paid, Paid, Cancelled
  final double paidAmount; // cumulative amount settled so far via one or more payments
  final String? paymentId;
  final String? receiptId;
  final String? notes;
  final bool isAutoGenerated;
  final String? cycleKey; // dedupe key: membershipId + dueDate (yyyy-MM-dd)
  final DateTime createdAt;
  final DateTime updatedAt;

  BillModel({
    required this.id,
    required this.billNumber,
    required this.memberId,
    required this.memberName,
    required this.memberPhone,
    this.membershipId,
    required this.planName,
    required this.amount,
    required this.billDate,
    required this.dueDate,
    required this.status,
    this.paidAmount = 0.0,
    this.paymentId,
    this.receiptId,
    this.notes,
    this.isAutoGenerated = false,
    this.cycleKey,
    required this.createdAt,
    required this.updatedAt,
  });

  bool get isPaid => status == 'Paid';
  bool get isPartiallyPaid => status == 'Partially Paid';
  bool get isCancelled => status == 'Cancelled';
  bool get isDue => status == 'Pending' || status == 'Overdue' || status == 'Partially Paid';
  double get remainingBalance => (amount - paidAmount) < 0 ? 0.0 : (amount - paidAmount);

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'billNumber': billNumber,
      'memberId': memberId,
      'memberName': memberName,
      'memberPhone': memberPhone,
      'membershipId': membershipId,
      'planName': planName,
      'amount': amount,
      'billDate': billDate.toIso8601String(),
      'dueDate': dueDate.toIso8601String(),
      'status': status,
      'paidAmount': paidAmount,
      'paymentId': paymentId,
      'receiptId': receiptId,
      'notes': notes,
      'isAutoGenerated': isAutoGenerated ? 1 : 0,
      'cycleKey': cycleKey,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
    };
  }

  factory BillModel.fromMap(Map<String, dynamic> map) {
    return BillModel(
      id: map['id'] ?? '',
      billNumber: map['billNumber'] ?? '',
      memberId: map['memberId'] ?? '',
      memberName: map['memberName'] ?? '',
      memberPhone: map['memberPhone'] ?? '',
      membershipId: map['membershipId'],
      planName: map['planName'] ?? '',
      amount: (map['amount'] ?? 0.0).toDouble(),
      billDate: DateTime.parse(map['billDate']),
      dueDate: DateTime.parse(map['dueDate']),
      status: map['status'] ?? 'Pending',
      paidAmount: (map['paidAmount'] ?? 0.0).toDouble(),
      paymentId: map['paymentId'],
      receiptId: map['receiptId'],
      notes: map['notes'],
      isAutoGenerated: (map['isAutoGenerated'] ?? 0) == 1,
      cycleKey: map['cycleKey'],
      createdAt: map['createdAt'] != null ? DateTime.parse(map['createdAt']) : DateTime.now(),
      updatedAt: map['updatedAt'] != null ? DateTime.parse(map['updatedAt']) : DateTime.now(),
    );
  }

  BillModel copyWith({
    String? id,
    String? billNumber,
    String? memberId,
    String? memberName,
    String? memberPhone,
    String? membershipId,
    String? planName,
    double? amount,
    DateTime? billDate,
    DateTime? dueDate,
    String? status,
    double? paidAmount,
    String? paymentId,
    String? receiptId,
    String? notes,
    bool? isAutoGenerated,
    String? cycleKey,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return BillModel(
      id: id ?? this.id,
      billNumber: billNumber ?? this.billNumber,
      memberId: memberId ?? this.memberId,
      memberName: memberName ?? this.memberName,
      memberPhone: memberPhone ?? this.memberPhone,
      membershipId: membershipId ?? this.membershipId,
      planName: planName ?? this.planName,
      amount: amount ?? this.amount,
      billDate: billDate ?? this.billDate,
      dueDate: dueDate ?? this.dueDate,
      status: status ?? this.status,
      paidAmount: paidAmount ?? this.paidAmount,
      paymentId: paymentId ?? this.paymentId,
      receiptId: receiptId ?? this.receiptId,
      notes: notes ?? this.notes,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      cycleKey: cycleKey ?? this.cycleKey,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}
