import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:uuid/uuid.dart';
import '../../core/theme/app_theme.dart';
import '../../core/localization/app_translations.dart';
import '../../core/services/app_state_service.dart';
import '../../core/utils/form_validators.dart';
import '../../data/models/bill_model.dart';
import '../../data/models/member_model.dart';
import '../../data/models/membership_model.dart';
import '../../data/repositories/bill_repository.dart';
import '../../shared/widgets/custom_text_field.dart';
import '../../shared/widgets/neon_button.dart';
import 'bill_detail_screen.dart';

class GenerateBillScreen extends StatefulWidget {
  final MemberModel member;
  final MembershipModel? membership;

  const GenerateBillScreen({
    super.key,
    required this.member,
    this.membership,
  });

  @override
  State<GenerateBillScreen> createState() => _GenerateBillScreenState();
}

class _GenerateBillScreenState extends State<GenerateBillScreen> {
  final _formKey = GlobalKey<FormState>();
  final _billRepo = BillRepository();

  late TextEditingController _amountController;
  late TextEditingController _notesController;

  DateTime _dueDate = DateTime.now();
  bool _isLoading = false;
  String _generatedBillNo = '';

  @override
  void initState() {
    super.initState();
    _amountController = TextEditingController(
      text: (widget.membership?.feeAmount ?? 0).toStringAsFixed(0),
    );
    _notesController = TextEditingController();
    if (widget.membership != null) {
      _dueDate = widget.membership!.endDate.isAfter(DateTime.now()) ? widget.membership!.endDate : DateTime.now();
    }
    _loadBillNumber();
  }

  @override
  void dispose() {
    _amountController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  Future<void> _loadBillNumber() async {
    final no = await _billRepo.generateNextBillNumber();
    if (mounted) setState(() => _generatedBillNo = no);
  }

  Future<void> _generateBill() async {
    if (!_formKey.currentState!.validate()) return;
    setState(() => _isLoading = true);

    const uuid = Uuid();
    final now = DateTime.now();
    final amount = double.parse(_amountController.text.trim());

    final bill = BillModel(
      id: uuid.v4(),
      billNumber: _generatedBillNo,
      memberId: widget.member.id,
      memberName: widget.member.name,
      memberPhone: widget.member.phone,
      membershipId: widget.membership?.id,
      planName: widget.membership?.planName ?? tr('generate_bill_membership_fee_fallback'),
      amount: amount,
      billDate: now,
      dueDate: _dueDate,
      status: 'Pending',
      notes: _notesController.text.trim().isNotEmpty ? _notesController.text.trim() : null,
      isAutoGenerated: false,
      cycleKey: widget.membership != null ? BillRepository.cycleKeyFor(widget.membership!.id, _dueDate) : null,
      createdAt: now,
      updatedAt: now,
    );

    await _billRepo.createBill(bill);
    AppStateService.instance.notifyBillsChanged();

    if (mounted) {
      setState(() => _isLoading = false);
      Navigator.pushReplacement(
        context,
        MaterialPageRoute(builder: (context) => BillDetailScreen(bill: bill)),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final dateFormat = DateFormat('dd MMM yyyy');

    return Scaffold(
      appBar: AppBar(
        title: Text(tr('generate_bill_title')),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: EdgeInsets.fromLTRB(24, 24, 24, 24 + MediaQuery.paddingOf(context).bottom),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: AppTheme.darkSurface,
                    borderRadius: BorderRadius.circular(20),
                    border: Border.all(color: AppTheme.darkBorder),
                  ),
                  child: Row(
                    children: [
                      CircleAvatar(
                        backgroundColor: AppTheme.neonLime,
                        child: Text(
                          widget.member.name.isNotEmpty ? widget.member.name[0].toUpperCase() : 'M',
                          style: const TextStyle(fontWeight: FontWeight.bold, color: AppTheme.darkBackground),
                        ),
                      ),
                      const SizedBox(width: 14),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(widget.member.name, style: const TextStyle(color: AppTheme.textWhite, fontWeight: FontWeight.bold, fontSize: 16)),
                            Text(widget.member.phone, style: const TextStyle(color: AppTheme.textMuted, fontSize: 12)),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 16),

                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(tr('generate_bill_number_label'), style: const TextStyle(color: AppTheme.textMuted, fontSize: 11, fontWeight: FontWeight.w800)),
                    Text(
                      _generatedBillNo,
                      style: TextStyle(color: AppTheme.neonLime, fontWeight: FontWeight.w900, fontSize: 14),
                    ),
                  ],
                ),
                const SizedBox(height: 16),

                CustomTextField(
                  label: 'Bill Amount (₹) *',
                  hint: '1500',
                  controller: _amountController,
                  keyboardType: const TextInputType.numberWithOptions(decimal: true),
                  validator: (v) => FormValidators.validateAmount(v, fieldName: 'Bill Amount'),
                ),
                const SizedBox(height: 16),

                const Text('DUE DATE', style: TextStyle(color: AppTheme.textMuted, fontSize: 11, fontWeight: FontWeight.w800)),
                const SizedBox(height: 6),
                InkWell(
                  onTap: () async {
                    final picked = await showDatePicker(
                      context: context,
                      initialDate: _dueDate,
                      firstDate: DateTime(2020),
                      lastDate: DateTime(2035),
                    );
                    if (picked != null && mounted) setState(() => _dueDate = picked);
                  },
                  child: Container(
                    width: double.infinity,
                    padding: const EdgeInsets.all(14),
                    decoration: BoxDecoration(color: AppTheme.darkBackground, borderRadius: BorderRadius.circular(14), border: Border.all(color: AppTheme.darkBorder)),
                    child: Text(dateFormat.format(_dueDate), style: const TextStyle(color: AppTheme.textWhite, fontWeight: FontWeight.bold)),
                  ),
                ),
                const SizedBox(height: 16),

                CustomTextField(
                  label: 'Notes (Optional)',
                  hint: 'e.g. Renewal bill for next cycle',
                  controller: _notesController,
                ),
                const SizedBox(height: 32),

                NeonButton(
                  text: 'Generate Bill',
                  width: double.infinity,
                  isLoading: _isLoading,
                  onPressed: _generateBill,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
